---
werc_site: luvi.net
werc_site_tag: luvi_net

werc_about_banners:
  - "name": "made-with-vim"
    "src": "/_assets/vim.gif"
    "url": null
  - "name": "compatible-with-chawan"
    "src": "https://chawan.net/banner/compatible_with_chawan.png"
    "url": "https://chawan.net/"

werc_people_links:
  - "name": "ericmaala.com"
    "url": "https://ericmaala.com"
    "desc": "Friend's photagraphy website."
  - "name": "melonland"
    "url": "https://melonland.net/"
    "desc": "Melon is a visual artist and wrote the [manifesto](https://melonking.net/thoughts/manifesto) on [The Web Revival](https://wiki.melonland.net/web_revival)"
  - "name": "Veronica Explains"
    "url": "https://veronicaexplains.net/"
    "desc": "Veronica's channel is the closest thing to what I would tried to do with a YouTube channel. Watch her [video](https://www.youtube.com/watch?v=4_bYUVGgQQo) on static site generators!"
  - "name": "mwl.io"
    "url": "https://mwl.io/"
    "desc": "One of my favorite authors in the techonology space."
  - "name": "rjeskow.com"
    "url": "https://www.rjeskow.com/"
    "desc": "Thank you for helping reconcile my thoughts on AI."
  - "name": "stallman.org"
    "url": "https://stallman.org/"
    "desc": "Much like the individual, this page is absurdly fascinating."
  - "name": "Digitama Hatchery"
    "url": "https://humulos.com/digimon/"
    "desc": "Digimon VPet database."
  - "name": "PPcenter"
    "url": "https://ppcenter.webou.net/news/"
    "desc": "Indie Saturn development."
  - "name": "On being a webmaster"
    "url": "https://justinjackson.ca/webmaster/"
    "desc": "I can relate..."
