stages:
  - test
  - secret-detection
  - deploy

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'

secret_detection:
  stage: secret-detection

deploy luvi.net:
  stage: deploy
  image: alpine/ansible:2.18.6
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  variables:
    ANSIBLE_HOST_KEY_CHECKING: 'False'
  script:
    - cd ansible/
    - ansible -u gitlab -m ping -i inventories/www.ini --key-file $SSH_PRIVATE_KEY all
