---
enabled_werc_sites:
  - luvi.net
  - gameboy.luvi.net
  - memes.luvi.net

werc_projects:
  - emoji: "&#x1F3AE;"
    name: "gameboy.luvi.net"
    url: "https://gameboy.luvi.net/"
    desc: "128×128px photography from a Game Boy Camera."
    meta_desc: null
  - emoji: "&#x1F3B4;"
    name: "flowercards.games"
    url: "https://flowercards.games/"
    desc: "&#x1F6A7; WIP Hanafuda video game blog."
    meta_desc: null
  - emoji: "&#x1F5C3;"
    name: "memes.luvi.net"
    url: "https://memes.luvi.net/"
    desc: "A junk drawer of memes."
    cc_exception: "Memes are for shared commentary and not covered by the following license; rights belong to their original creators,"
    meta_desc: null
  - emoji: "&#x1F4F7;"
    name: "luisviant.com"
    url: "https://luisviant.com/"
    desc: "Personal photography portfolio."
  - emoji: "&#x1F4E1;"
    name: "live.luvi.net"
    url: "https://live.luvi.net/"
    desc: "Somewhere I can broadcast my livestreams to, because _fuck_ Bezos. ([_some JavaScript_](https://github.com/video-dev/hls.js/))"
