---
enabled_werc_sites:
  - luvi.net
  - gameboy.luvi.net
  - memes.luvi.net

werc_projects:
  - emoji: "&#x1F3AE;"
    label: "gameboy"
    name: "gameboy.luvi.net"
    url: "https://gameboy.luvi.net"
    desc: "128×128px photography from a Game Boy Camera."
  - emoji: "&#x1F3B4;"
    label: "hanafuda"
    name: "flowercards.games"
    url: "https://flowercards.games"
    desc: "&#x1F6A7; WIP Hanafuda video game blog."
  - emoji: "&#x1F5C3;"
    label: "memes"
    name: "memes.luvi.net"
    url: "https://memes.luvi.net"
    desc: "A junk drawer of memes."
  - emoji: "&#x1F4F7;"
    label: "photography"
    name: "luisviant.com"
    url: "https://luisviant.com"
    target_blank: true
    desc: "Personal photography portfolio."
  - emoji: "&#x1F4E1;"
    label: "live"
    name: "live.luvi.net"
    url: "https://live.luvi.net"
    target_blank: true
    desc: "Somewhere I can broadcast my livestreams to, because _fuck_ Bezos. ([_some JavaScript_](https://github.com/video-dev/hls.js/))"
