<div></div>

<div>
	{% if werc_site == 'memes.luvi.net' %}<small class="copyright__content">Memes are shared for commentary and aren't covered by the license; rights belong to their original creators,</small>{% endif %}
	<small class="copyright__content">
		<a href="https://luvi.net/">luvi.net</a> &copy; {{ now(fmt='%Y') }} by <a href="https://luvi.net/about">Luis Viant</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a> &#x1F16D;&#x1F16F;&#x1F10F;&#x1F10E;,
	</small>
	<small class="copyright__content"><a href="http://werc.cat-v.org/" target="_blank">Powered by werc</a></small>
</div>

<div></div>
