<div></div>

<div class="h-card">
	{% if werc_site == 'memes.luvi.net' %}<small class="copyright__content">Memes are shared for commentary and aren't covered by the license; rights belong to their original creators,</small>{% endif %}
	<small class="copyright__content"><a class="h-card p-org u-url u-uid" href="https://luvi.net/">luvi.net</a> &copy {{ now(fmt='%Y') }} by <a class="p-name" href="https://luvi.net/about">Luis Viant</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a> &#x1F16D&#x1F16F&#x1F10F&#x1F10E,</small>
	<small class="copyright__content"><a href="http://werc.cat-v.org/" target="_blank">Powered by werc</a></small>
	<div hidden>
		<img class="u-photo" src="https://avatars.githubusercontent.com/u/5025623?s=400&u=cbd54fd93869db9cb15683e9e852cf4c7f543f04&v=4"></img>
		<span class="p-note">Hello, I'm Lu &#x1F44B; I'm a tech worker and evangelist, infrastructure engineer, fledgling Go programmer, and photographer. This site is a collection of my thoughts, art, projects and interests in the form of a <i>lo-web</i> home page notwithstanding a lack a social media engagement.</span>
	</div>
</div>

<div></div>
